### ISSUE TITLE
Make from scoped, and its result renamable

### ISSUE THREAD

**Issue by duckinator** [ruby-heresy/from#1]
_(Copied from GitLab: https://gitlab.com/spinny/from/issues/1)_

```ruby
module F
  def foo
    z = from('x').import(:Y)
  end
end
```

`X::Y` is now available as `z`, but only in `F::foo`. i.e. Just like modules work in lua and es6.

**Comment by duckinator** [comment]
Keeping note of this for later (again): https://github.com/soveran/cargo/blob/master/lib/cargo.rb

**Comment by duckinator** [comment]
Idea:

Rename `From#import` to `From#include` (since it behaves as a partial `include`):

```ruby
from('net/socket').include(:TCP, :UDP)
# TCP == Net::Socket::TCP
# UDP == Net::Socket::UDP
```

and replace `import` with one that simply returns the values:

```ruby
tcp, udp = from('net/socket').import(:TCP, :UDP)
```

`import` would still leak `Net::Socket` in this example, and I don't think I can get around that, but it wouldn't create `TCP` or `UDP`.

Thoughts?

cc @igalic because you opened the original GitLab issue.
cc @krainboltgreene because you seem to have interesting thoughts on things like this.

**Comment by duckinator** [comment]
I think the names actually look a bit too similar. Perhaps include and get?

I mostly just don't want to have to do this:

```ruby
TCP, UDP = from('net/socket').import(:TCP, :UDP)
```

**Comment by duckinator** [comment]
Alternatively, I could do `.import!` (defines constants) and `.import` (doesn't define constants).

**Comment by krainboltgreene** [comment]
@duckinator I like the difference between include and import here, definitely felt right when I tested it out.

**Comment by duckinator** [comment]
I think I'm going to go with `include` and `import`. It might take me a bit to get around to actually working on it, but yeah.

It should in theory be relatively straightforward to implement if anyone else wants to take a whack at it.

* [ ] Rename `import` to `include`.
* [ ] Add `import`.

Return should be something like:

```ruby
def import(*constants)
  ret = constants.map { |const_name| const_grep(@module, const_name) }

  if ret.length == 1
    ret.first
  else
    ret
  end
end
```

But it also needs tests and such.

**Comment by duckinator** [comment]
I'm taking the fact that I unintentionally named it `import` instead of `return` as a hint that that's a better name.

**Comment by duckinator** [comment]
Done! :3
